import type { MeetingSummary, ExportFormat } from '../types'
import { formatCurrency, formatDurationHuman, formatDateTime } from './formatters'

/**
 * Export meeting summary as JSON
 */
export const exportAsJson = (summary: MeetingSummary): string => {
  return JSON.stringify(summary, null, 2)
}

/**
 * Export meeting summary as CSV
 */
export const exportAsCsv = (summary: MeetingSummary): string => {
  const headers = [
    'Meeting Title',
    'Date',
    'Duration',
    'Total Cost',
    'Attendee Count',
    'Avg Cost Per Attendee',
  ]

  const values = [
    summary.title,
    formatDateTime(summary.timestamp),
    formatDurationHuman(summary.duration),
    formatCurrency(summary.totalCost),
    summary.attendeeCount.toString(),
    formatCurrency(summary.averageCostPerAttendee),
  ]

  let csv = headers.join(',') + '\n'
  csv += values.map((v) => `"${v}"`).join(',') + '\n\n'

  // Add breakdown if available
  if (summary.costBreakdown.attendeeCosts.length > 0) {
    csv += '\nAttendee Breakdown\n'
    csv += 'Name,Hourly Rate,Total Cost\n'
    summary.costBreakdown.attendeeCosts.forEach((attendee) => {
      csv += `"${attendee.name}","${formatCurrency(attendee.hourlyRate)}/hr","${formatCurrency(attendee.totalCost)}"\n`
    })
  }

  return csv
}

/**
 * Generate HTML for PDF export
 */
export const generatePdfHtml = (summary: MeetingSummary): string => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Meeting Cost Summary - ${summary.title}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          max-width: 800px;
          margin: 40px auto;
          padding: 20px;
          color: #1a1a1a;
        }
        h1 { color: #0ea5e9; margin-bottom: 8px; }
        .subtitle { color: #666; margin-bottom: 24px; }
        .stats-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 16px;
          margin-bottom: 32px;
        }
        .stat-card {
          background: #f8fafc;
          padding: 16px;
          border-radius: 8px;
          text-align: center;
        }
        .stat-label { font-size: 12px; color: #666; text-transform: uppercase; }
        .stat-value { font-size: 24px; font-weight: bold; color: #0ea5e9; }
        .breakdown { margin-top: 24px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
        th { background: #f8fafc; font-weight: 600; }
        .total-row { font-weight: bold; background: #f0f9ff; }
        .footer { margin-top: 32px; font-size: 12px; color: #666; text-align: center; }
      </style>
    </head>
    <body>
      <h1>${summary.title}</h1>
      <p class="subtitle">${formatDateTime(summary.timestamp)}</p>

      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-label">Total Cost</div>
          <div class="stat-value">${formatCurrency(summary.totalCost)}</div>
        </div>
        <div class="stat-card">
          <div class="stat-label">Duration</div>
          <div class="stat-value">${formatDurationHuman(summary.duration)}</div>
        </div>
        <div class="stat-card">
          <div class="stat-label">Attendees</div>
          <div class="stat-value">${summary.attendeeCount}</div>
        </div>
      </div>

      <div class="breakdown">
        <h2>Cost Breakdown</h2>
        <table>
          <thead>
            <tr>
              <th>Attendee</th>
              <th>Hourly Rate</th>
              <th>Cost</th>
            </tr>
          </thead>
          <tbody>
            ${summary.costBreakdown.attendeeCosts
              .map(
                (a) => `
              <tr>
                <td>${a.name}</td>
                <td>${formatCurrency(a.hourlyRate)}/hr</td>
                <td>${formatCurrency(a.totalCost)}</td>
              </tr>
            `
              )
              .join('')}
            <tr class="total-row">
              <td>Total</td>
              <td>${formatCurrency(summary.costBreakdown.costPerHour)}/hr</td>
              <td>${formatCurrency(summary.totalCost)}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="footer">
        Generated by Meeting Cost Calculator
      </div>
    </body>
    </html>
  `
}

/**
 * Download file
 */
export const downloadFile = (
  content: string,
  filename: string,
  mimeType: string
): void => {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Export meeting summary
 */
export const exportMeetingSummary = (
  summary: MeetingSummary,
  format: ExportFormat
): void => {
  const timestamp = new Date().toISOString().split('T')[0]
  const safeTitle = summary.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()

  switch (format) {
    case 'json': {
      const content = exportAsJson(summary)
      downloadFile(content, `meeting-${safeTitle}-${timestamp}.json`, 'application/json')
      break
    }
    case 'csv': {
      const content = exportAsCsv(summary)
      downloadFile(content, `meeting-${safeTitle}-${timestamp}.csv`, 'text/csv')
      break
    }
    case 'pdf': {
      const html = generatePdfHtml(summary)
      const printWindow = window.open('', '_blank')
      if (printWindow) {
        printWindow.document.write(html)
        printWindow.document.close()
        printWindow.print()
      }
      break
    }
  }
}

/**
 * Copy summary to clipboard
 */
export const copyToClipboard = async (summary: MeetingSummary): Promise<boolean> => {
  const text = `Meeting: ${summary.title}
Date: ${formatDateTime(summary.timestamp)}
Duration: ${formatDurationHuman(summary.duration)}
Total Cost: ${formatCurrency(summary.totalCost)}
Attendees: ${summary.attendeeCount}
Average Cost Per Attendee: ${formatCurrency(summary.averageCostPerAttendee)}

Breakdown:
${summary.costBreakdown.attendeeCosts
  .map((a) => `- ${a.name}: ${formatCurrency(a.totalCost)} (${formatCurrency(a.hourlyRate)}/hr)`)
  .join('\n')}
`

  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    return false
  }
}
